# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-25 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20150904_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backend',
            name='klass',
            field=models.CharField(help_text='Example: notifier.backends.EmailBackend', max_length=500),
        ),
    ]
